<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'first_name' => 'Jane',
                'last_name' => 'Doe',
                'email' => 'jane.doe@example.com',
                'job_title' => 'Product Designer',
                'department' => 'design',
                'employment_type' => 'Full-time',
                'pay_type' => 'salary',
                'base_salary' => 8500.00,
                'hourly_rate' => null,
                'standard_hours' => 160,
                'allowances' => 450.00,
                'fixed_deductions' => 1200.00,
            ],
            [
                'first_name' => 'Mark',
                'last_name' => 'Smith',
                'email' => 'mark.smith@example.com',
                'job_title' => 'Frontend Engineer',
                'department' => 'engineering',
                'employment_type' => 'Full-time',
                'pay_type' => 'salary',
                'base_salary' => 7200.00,
                'hourly_rate' => null,
                'standard_hours' => 160,
                'allowances' => 300.00,
                'fixed_deductions' => 980.00,
            ],
            [
                'first_name' => 'Amelia',
                'last_name' => 'Lewis',
                'email' => 'amelia.lewis@example.com',
                'job_title' => 'Marketing Lead',
                'department' => 'marketing',
                'employment_type' => 'Full-time',
                'pay_type' => 'salary',
                'base_salary' => 9100.00,
                'hourly_rate' => null,
                'standard_hours' => 152,
                'allowances' => 600.00,
                'fixed_deductions' => 1450.00,
            ],
            [
                'first_name' => 'Robert',
                'last_name' => 'Wilson',
                'email' => 'robert.wilson@example.com',
                'job_title' => 'Backend Engineer',
                'department' => 'engineering',
                'employment_type' => 'Full-time',
                'pay_type' => 'salary',
                'base_salary' => 8800.00,
                'hourly_rate' => null,
                'standard_hours' => 168,
                'allowances' => 250.00,
                'fixed_deductions' => 1100.00,
            ],
            [
                'first_name' => 'Elena',
                'last_name' => 'Cruz',
                'email' => 'elena.cruz@example.com',
                'job_title' => 'UX Researcher',
                'department' => 'design',
                'employment_type' => 'Contract',
                'pay_type' => 'salary',
                'base_salary' => 6950.00,
                'hourly_rate' => null,
                'standard_hours' => 160,
                'allowances' => 400.00,
                'fixed_deductions' => 850.00,
            ],
            [
                'first_name' => 'David',
                'last_name' => 'Park',
                'email' => 'david.park@example.com',
                'job_title' => 'DevOps Engineer',
                'department' => 'engineering',
                'employment_type' => 'Full-time',
                'pay_type' => 'salary',
                'base_salary' => 8300.00,
                'hourly_rate' => null,
                'standard_hours' => 160,
                'allowances' => 350.00,
                'fixed_deductions' => 1050.00,
            ],
            [
                'first_name' => 'Sofia',
                'last_name' => 'Martinez',
                'email' => 'sofia.martinez@example.com',
                'job_title' => 'HR Specialist',
                'department' => 'hr',
                'employment_type' => 'Full-time',
                'pay_type' => 'salary',
                'base_salary' => 6400.00,
                'hourly_rate' => null,
                'standard_hours' => 160,
                'allowances' => 280.00,
                'fixed_deductions' => 920.00,
            ],
            [
                'first_name' => 'Liam',
                'last_name' => 'Chen',
                'email' => 'liam.chen@example.com',
                'job_title' => 'Data Analyst',
                'department' => 'engineering',
                'employment_type' => 'Part-time',
                'pay_type' => 'salary',
                'base_salary' => 7100.55,
                'hourly_rate' => null,
                'standard_hours' => 155,
                'allowances' => 320.00,
                'fixed_deductions' => 980.00,
            ],
            [
                'first_name' => 'Nora',
                'last_name' => 'Abdullah',
                'email' => 'nora.abdullah@example.com',
                'job_title' => 'Finance Manager',
                'department' => 'finance',
                'employment_type' => 'Full-time',
                'pay_type' => 'salary',
                'base_salary' => 9800.00,
                'hourly_rate' => null,
                'standard_hours' => 160,
                'allowances' => 500.00,
                'fixed_deductions' => 1600.00,
            ],
            [
                'first_name' => 'Owen',
                'last_name' => 'Blake',
                'email' => 'owen.blake@example.com',
                'job_title' => 'QA Engineer',
                'department' => 'engineering',
                'employment_type' => 'Full-time',
                'pay_type' => 'salary',
                'base_salary' => 6800.00,
                'hourly_rate' => null,
                'standard_hours' => 160,
                'allowances' => 220.00,
                'fixed_deductions' => 860.00,
            ],
        ];

        foreach ($employees as $employee) {
            Employee::updateOrCreate(
                ['email' => $employee['email']],
                [
                    'first_name' => $employee['first_name'],
                    'last_name' => $employee['last_name'],
                    'email' => $employee['email'],
                    'job_title' => $employee['job_title'],
                    'department' => $employee['department'],
                    'employment_type' => $employee['employment_type'],
                    'pay_type' => $employee['pay_type'],
                    'base_salary' => $employee['base_salary'],
                    'hourly_rate' => $employee['hourly_rate'],
                    'standard_hours' => $employee['standard_hours'],
                    'allowances' => $employee['allowances'],
                    'fixed_deductions' => $employee['fixed_deductions'],
                    'deduction_rate' => 0,
                    'is_active' => true,
                    'start_date' => now()->subMonth(),
                    'status' => 'active',
                    'work_location' => 'On-site',
                    'probation_period' => 'None',
                ]
            );
        }
    }
}
